# Generated by Django 4.2.4 on 2023-11-15 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClientNote',
            new_name='TrainerNote',
        ),
    ]
