# Generated by Django 4.2.4 on 2023-11-15 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0002_rename_clientnote_trainernote'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.JSONField(default=dict)),
                ('trainer_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='builder.trainerclient')),
            ],
        ),
        migrations.CreateModel(
            name='ClientNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='builder.program')),
                ('trainer_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_notes', to='builder.trainerclient')),
            ],
        ),
        migrations.CreateModel(
            name='ClientInjuries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('injury_name', models.CharField(max_length=50)),
                ('injury_type', models.CharField(choices=[('sprain', 'Sprain'), ('strain', 'Strain'), ('fracture', 'Fracture'), ('dislocation', 'Dislocation'), ('tendonitis', 'Tendonitis'), ('bursitis', 'Bursitis'), ('disc herniation', 'Disc Herniation'), ('other', 'Other')], max_length=50)),
                ('site', models.CharField(choices=[('head', 'Head'), ('neck', 'Neck'), ('shoulder', 'Shoulder'), ('elbow', 'Elbow'), ('wrist', 'Wrist'), ('hand', 'Hand'), ('hip', 'Hip'), ('back', 'Back'), ('chest', 'Chest'), ('abdomen', 'Abdomen'), ('upper_back', 'Upper Back'), ('lower_back', 'Lower Back'), ('groin', 'Groin'), ('thigh', 'Thigh'), ('hamstring', 'Hamstring'), ('knee', 'Knee'), ('ankle', 'Ankle'), ('foot', 'Foot'), ('other', 'Other')], default='other', max_length=50)),
                ('laterality', models.CharField(choices=[('left', 'Left'), ('right', 'Right'), ('both', 'Both')], default='both', max_length=10)),
                ('date_of_injury', models.DateField()),
                ('pain_when', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('healed', 'Healed'), ('severe', 'Severe'), ('chronic', 'Chronic'), ('other', 'Other')], max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('trainer_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='injuries', to='builder.trainerclient')),
            ],
            options={
                'ordering': ['-date_of_injury'],
            },
        ),
        migrations.CreateModel(
            name='ClientGoals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('goal_type', models.CharField(choices=[('long', 'Long'), ('med', 'Medium'), ('short', 'Short'), ('long', 'Long'), ('longer', 'Longer'), ('longest', 'Longest')], max_length=7)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('goal_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('abandoned', 'Abandoned'), ('complete', 'Complete')], default='active', max_length=10)),
                ('trainer_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='builder.trainerclient')),
            ],
            options={
                'ordering': ['goal_date'],
            },
        ),
        migrations.CreateModel(
            name='ClientData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='builder.clientgoals')),
                ('injuries', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='builder.clientinjuries')),
                ('notes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='builder.clientnotes')),
                ('preferences', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='builder.clientpreferences')),
                ('trainer_client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_data', to='builder.trainerclient')),
            ],
        ),
    ]
