# Generated by Django 4.2.4 on 2023-10-03 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0003_officialbeginnertemplate_alter_accountmetrics_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmetrics',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='account_metrics', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
