# Generated by Django 4.2.4 on 2023-11-16 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0003_clientpreferences_clientnotes_clientinjuries_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientgoals',
            name='goal_type',
            field=models.CharField(choices=[('long', 'Long'), ('med', 'Medium'), ('short', 'Short')], max_length=7),
        ),
    ]
