# Generated by Django 4.2.4 on 2023-11-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0004_alter_clientgoals_goal_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientdata',
            name='goals',
        ),
        migrations.RemoveField(
            model_name='clientdata',
            name='injuries',
        ),
        migrations.RemoveField(
            model_name='clientdata',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='clientdata',
            name='preferences',
        ),
        migrations.AddField(
            model_name='clientdata',
            name='goals',
            field=models.ManyToManyField(blank=True, to='builder.clientgoals'),
        ),
        migrations.AddField(
            model_name='clientdata',
            name='injuries',
            field=models.ManyToManyField(blank=True, to='builder.clientinjuries'),
        ),
        migrations.AddField(
            model_name='clientdata',
            name='notes',
            field=models.ManyToManyField(blank=True, to='builder.clientnotes'),
        ),
        migrations.AddField(
            model_name='clientdata',
            name='preferences',
            field=models.ManyToManyField(blank=True, to='builder.clientpreferences'),
        ),
    ]
