name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DB_HOST: localhost
      DB_PORT: 5432
      DB_NAME: test_db
      DB_PASSWORD: postgres
      DB_USER: postgres

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Python setup
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Install Python dependencies and test backend
        run: |
          cd backend/programbuilder
          pip install -r requirements.txt
          python manage.py test

      # Node.js setup
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      # Frontend build and test
      - name: Build and test frontend
        run: |
          cd frontend/svelte-app
          npm install
          npm test
          npm run build
