name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Python setup
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Install Python dependencies
        run: cd backend/programbuilder
          pip install -r requirements.txt

      - name: Run Django tests
        run: python manage.py test

      # Node.js setup
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      # Frontend build and test
      - name: Build and test frontend
        run: |
          cd frontend/svelte-app
          npm install
          npm test
          npm run build
